services:
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: soketi
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_DEFAULT_APP_ID: "my-id"
      SOKETI_DEFAULT_APP_KEY: "my-key"
      SOKETI_DEFAULT_APP_SECRET: "my-secret"
      SOKETI_ALLOWED_ORIGINS: "http://localhost:8000"